const axios = require('axios');
const cheerio = require('cheerio');

// axios -> sends the request to Amazon servers and receives a response
// cheerio -> manipulates amazon response and the html in response body, extracting the necessary data

// web scraping function
const amazonSearchScrape = (req, res) => {

    // keyword that will be searched on Amazon
    const keyword = req.params.keyword;

    // array for storage the searched data
    // image, title, rating number and rating reviews number
    let products = [];

    axios.get('https://www.amazon.com.br/s', {
            params: {
                k: keyword
            },
            headers: {
                Accept: "application/json",
                "User-Agent": "axios 0.21.1"    
            }
        })
        .then(res => {
            // load the html content using cheerio
            const $ = cheerio.load(res.data); 


            // this was the pattern i detected on amazon product pages
            // every html element containing a products data has a 'data-asin' attribute
            // asin is a code of 10 unique alphanumeric characters for each product registered on Amazon
            // $('[data-asin!=""]') -> return a list of elements that have the non-null data-asin attribute
            $('[data-asin!=""]').each((index, element) => {

                // product title
                const productTitle = $(element).find('.s-title-instructions-style > h2').text();

                // product rating
                let productRating = $(element).find('.a-icon-star-small').text();
                
                // extract 'x' rating number of pattern string 'x de 5 estrelas'
                if (productRating) {
                    productRating = productRating.split(' ');
                    if (productRating[0].length > 1) 
                        productRating = productRating[0][0] + '.' + productRating[0][2];
                }

                // product review
                const productReviews = $(element).find('.a-link-normal.s-underline-text.s-underline-link-text.s-link-style > .a-size-base.s-underline-text').text();

                // product img
                const productImg = $(element).find('.s-image').attr('src');

                // not all amazon products have ratings and reviews
                // but all amazon products have a title and an image (even if it is that null image generated by amazon)
                if (productTitle && productImg) {
                    products.push({
                        title: productTitle,
                        rating: productRating,
                        reviews: productReviews,
                        imgUrl: productImg
                    });
                }
            })

            console.log(`${products.length} items founded in amazon search with '${keyword}' keyword`);
        })
        .catch(error => {
            console.log(error);
            return res.status(500).send({message: 'Internal server error', error}).end();
        })
        .finally(() => {
            // return list of products to client in json format
            return res.status(200).send({products}).end();
        });
};

module.exports = amazonSearchScrape;